### PR TITLE
Fix scalaz interpreter

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Finally got around to fixing these tests. Conditional operations reify corresponding exceptions in the happy path, only those operations needed adjusting.

cc @emilypi

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
Those build failures are 😲

**Comment by philwills** [comment]
Sorry for not reviewing. I wonder if your work on the build means that some of the extra shutdown calls can now be removed.

**Comment by regiskuckaertz** [comment]
They're not fundamental indeed, I just thought a test suite creates a client and then shuts it down.

**Comment by regiskuckaertz** [comment]
@emilypi We need to design a proper error ADT, `ConditionalCheckFailedException` only fits a few use cases and is a throwable. Then I totally agree we'll be able to use the full expressiveness of zio.

In hindsight, I could have fixed it by just `attempt`ing the conditional operations as they expect an `Either[ConditionalCheckFailedException, A0]` in return.

**Pull request merged**
