### PR TITLE
Add a module to support refined types

### PR DESCRIPTION
**Pull request by alonsodomin**
Hi all, hope you find this interesting.

At work we use refined types in some projects so we end up writing wiring (integration?) with other libraries that do not support it. Most of the time the code is as trivial as in this case, so I took the liberty of adding a module to the project to support them so everyone else can also profit from it.

### CODE REVIEW

**Comment by alonsodomin** [comment]
it seems that there is no much interest in this piece of code... I wouldn't mind to release it under a different `groupId` but it would be great to get some sort of feedback...

**Comment by philwills** [comment]
Sorry, not lack of interest, just haven't been finding time to keep up. Thankfully some of my former colleagues are planning to help out.

**Comment by philwills** [comment]
Thanks @alonsodomin, this looks great.

**Comment by alonsodomin** [comment]
@philwills wow, that was fast! thanks for considering! :)

**Comment by philwills** [comment]
@davidfurey did  a release, but I failed to notice that this wasn't aggregated into the root SBT project, so it hasn't been released. I think it should be possible to release just this module by checking out the tag and publishing from within the refined project, but it may be safer just to do another release.

I've opened #194 to hopefully mean it will consistently get released in future.

**Comment by davidfurey** [comment]
@philwills - I tried just publishing the refined module but it didn't work.  If there is no objections I'll just do another release rather than spend time investigating why it failed.

**Comment by philwills** [comment]
:+1:

**Comment by davidfurey** [comment]
Done

**Pull request merged**
