### PR TITLE
Add ability to override default in `*xmap`

### LINKED ISSUE #424: Upgrading from 1.0.0-M5 to M10 broke a custom DynamoFormat for Instant
This is a cutdown version of some code we were using in 1.0.0-M5, with a custom formatter for Instant because Scanamo didn’t provide one:

```scala
import java.time.Instant

import com.gu.scanamo._
import com.gu.scanamo.error.DynamoReadError
import com.gu.scanamo.ops.ScanamoOps
import com.gu.scanamo.{DynamoFormat, Table}


case class Birthday(name: String, time: Instant)


object Main extends App {
  implicit val instantStringFormat = DynamoFormat.coercedXmap[Instant, String, IllegalArgumentException](
    Instant.parse(_)
  )(
    _.toString
  )

  val table = Table[Birthday]("birthdays")

  val birthday = Birthday(name = "Alex", time = Instant.now())

  val ops: ScanamoOps[Option[Either[DynamoReadError, Birthday]]] = table.put(birthday)
  println(ops)
}
```

This code would correctly store an Instant in DynamoDB as an ISO-8601 date string.

We upgraded to 1.0.0-M10 and tweaked the imports as follows:

```scala
import java.time.Instant

import org.scanamo.auto._
import org.scanamo.error.DynamoReadError
import org.scanamo.ops.ScanamoOps
import org.scanamo.{DynamoFormat, Table}


case class Birthday(name: String, time: Instant)


object Main extends App {
  implicit val instantStringFormat = DynamoFormat.coercedXmap[Instant, String, IllegalArgumentException](
    Instant.parse(_)
  )(
    _.toString
  )

  val table = Table[Birthday]("birthdays")

  val birthday = Birthday(name = "Alex", time = Instant.now())

  val ops: ScanamoOps[Option[Either[DynamoReadError, Birthday]]] = table.put(birthday)
  println(ops)
}
```

Running the same code now throws an error:

```
[error] (run-main-0) java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
[error] java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
[error] 	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
[error] 	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
[error] 	at java.time.Instant.parse(Instant.java:395)
[error] 	at Main$.$anonfun$instantStringFormat$1(Main.scala:14)
[error] 	at org.scanamo.DynamoFormat$.$anonfun$coerce$2(DynamoFormat.scala:203)
[error] 	at cats.syntax.EitherSyntax$CatchOnlyPartiallyApplied$.apply$extension(either.scala:31)
[error] 	at org.scanamo.DynamoFormat$.$anonfun$coerce$1(DynamoFormat.scala:203)
[error] 	at org.scanamo.DynamoFormat$$anon$3.$anonfun$default$1(DynamoFormat.scala:134)
[error] 	at scala.Option.flatMap(Option.scala:171)
[error] 	at org.scanamo.DynamoFormat$$anon$3.<init>(DynamoFormat.scala:134)
[error] 	at org.scanamo.DynamoFormat$.xmap(DynamoFormat.scala:131)
[error] 	at org.scanamo.DynamoFormat$.coercedXmap(DynamoFormat.scala:157)
[error] 	at Main$.delayedEndpoint$Main$1(Main.scala:15)
[error] 	at Main$delayedInit$body.apply(Main.scala:12)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at Main$.main(Main.scala:12)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

For some reason an empty string is being passed into our custom `DynamoFormat` mapper, and it throws an exception when we construct the Put operation.

It’s not clear why this is throwing, or indeed why the (string) ~> (Instant) formatter is being used in a Put operation – and although the new Instant formats in Scanamo itself are nice, that's no good for existing tables that are stored in the old format.

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Closes #424

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
You're right, let's add some!

**Comment by regiskuckaertz** [comment]
I don't see the value in having a separate project for formats; it is central to the library. Let's bring it into the core project!

**Comment by regiskuckaertz** [comment]
> Option of Option?

Yes 😆 If you think about it, a default value is an `Option[A]`. You _may_ want to override that value, which means you may want it to be `None`. But how would you differentiate between (1) not wanting to override the default and (2) overriding it to `None` with just an `Option[A]`?

That's a bit convoluted, but I can't find a better way to express that.

**Comment by regiskuckaertz** [comment]
@TBonnin now good for final review 😄

**Comment by TBonnin** [comment]
> > Option of Option?
> 
> Yes 😆 If you think about it, a default value is an `Option[A]`. You _may_ want to override that value, in particular you may want it to be `None`. But how would you differentiate between (1) not wanting to override the default and (2) overriding it to `None` with just an `Option[A]`?
> 
> That's a bit convoluted, but I can't find a better way to express that.

I see what you mean but I feel the meaning of the two level of `Option` requires a split second of thinking. I would prefer it was more obvious.
What about a simple ADT to express better what the first level `Option` means. Not sure it is not an overkill though. 

Ex:
```
sealed trait Xdefault[+A]
case class Cons[A](default: Option[A]) extends Xdefault[A]
case object NoDefault extends Xdefault[Nothing]

object Xdefault {
   def apply[A](default: Option[A]): Xdefault[A] = Cons(default)
}
```

**Comment by regiskuckaertz** [comment]
I like that! Let me work this out.

**Pull request merged**
