### PR TITLE
migrate to gh actions

### PR DESCRIPTION
**Pull request by i10416**
prepare for #1465 ,#1577

This PR migrates ci from Travis to GitHub Actions.

I found current ci does not publish docsite, so I keep it as is. 
I guess it takes much to find out how docsite is published currently and incorporate into ci workflow. Therefore, I put publishing docsite aside for now.

Workflow runs format check, lint and tests against Scala version 2.15.16 and 2.13.8.

To enable auto release, please set the environment variables bellow from settings page

- PGP_PASSPHRASE
- PGP_SECRET
- SONATYPE_PASSWORD
- SONATYPE_USERNAME
image

After setting secrets, GitHub Actions will publish pre-release artifact on every PR(after lint and test) and release artifact on tag.

If you have trouble, see https://github.com/sbt/sbt-ci-release

### CODE REVIEW

**Comment by kailuowang** [comment]
Thanks so much!
@rtyley looks like a *scanamo* user was approved by sonatype to have publishing right. 
https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-44688

Maybe you have the credential of it that we can use for ci release?

**Comment by rtyley** [comment]
> * PGP_PASSPHRASE
> * PGP_SECRET
> * SONATYPE_PASSWORD
> * SONATYPE_USERNAME

I've added these repository secrets (using the 'scanamo' sonatype user, and [this](https://keyserver.ubuntu.com/pks/lookup?search=6ba6fe75e815f1598d5ec033708a8df538f1bcdd&fingerprint=on&op=index) PGP key. I'll merge now and try to perform a release...

**Comment by rtyley** [comment]
I tagged the latest commit (c84bf7802ce52daec8a105becd955e540411abe1) as [v1.0.0-M21](https://github.com/scanamo/scanamo/releases/tag/v1.0.0-M21), and I can see that a release step occurred, it's still running...

https://github.com/scanamo/scanamo/actions/runs/3339137076/jobs/5527814974

**Comment by kailuowang** [comment]
Thanks so much Tyley! I got a M22 release.

**Comment by i10416** [comment]
@rtyley  Thank you!

**Comment by i10416** [comment]
@rtyley Do you have right to generate credentials for s01.oss.sonatype.org?

rel
- https://github.com/sbt/sbt-ci-release/issues/181#issuecomment-804540949
- https://github.com/sbt/sbt-ci-release/issues/181

**Comment by kailuowang** [comment]
I think we can disable snapshot publish for now ( we don't have frequent bug fixes or features, and it's very easy to release a new milestone) if s01.oss.sonatype.org is too much

**Comment by i10416** [comment]
I agree! Disabled in https://github.com/scanamo/scanamo/pull/1594.

**Pull request merged**
