### PR TITLE
Run DynamodbLocal while microsite is building

### PR DESCRIPTION
**Pull request by davidfurey**
The code snippets in the microsite need DynamodbLocal to be running to work.

### CODE REVIEW

**Review by regiskuckaertz — APPROVED** [review]
Good spot!

**Comment by davidfurey** [comment]
@regiskuckaertz unfortunately the microsite still isn't updating.  The error in travis is:
```
Error making request to GitHub
	at microsites.github.GitHubOps.$anonfun$run$1(GitHubOps.scala:208)
	at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
	at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
	at flatMap @ org.http4s.client.PoolManager.releaseRecyclable(PoolManager.scala:225)
	at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
	at unsafeRunSync @ microsites.MicrositeAutoImportSettings.$anonfun$micrositeTasksSettings$14(MicrositeKeys.scala:496)
	at withPermit @ org.http4s.client.PoolManager.shutdown(PoolManager.scala:370)
	at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
	at withPermit @ org.http4s.client.PoolManager.shutdown(PoolManager.scala:370)
	at guarantee$extension @ org.http4s.client.blaze.Http1Connection.$anonfun$executeRequest$2(Http1Connection.scala:193)
	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
Caused by: UnauthorizedError(Bad credentials, https://docs.github.com/rest)
```
https://travis-ci.org/github/scanamo/scanamo/jobs/758235897

Would you mind taking a look?

**Comment by regiskuckaertz** [comment]
Oouh so Github Rest authentication problem, let me have a look

–Regis

On February 9, 2021, Nicolas Stucki <notifications@github.com> wrote:
> @regiskuckaertz <https://github.com/regiskuckaertz> unfortunately the

> microsite still isn't updating. The error in travis is:
>
> Error making request to GitHub at
> microsites.github.GitHubOps.$anonfun$run$1(GitHubOps.scala:208) at
> uncancelable @
> org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)

> at uncancelable @
> org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)

> at flatMap @
> org.http4s.client.PoolManager.releaseRecyclable(PoolManager.scala:225)

> at uncancelable @
> org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)

> at unsafeRunSync @
> microsites.MicrositeAutoImportSettings.$anonfun$micrositeTasksSettings$14(MicrositeKeys.scala:496)
> at withPermit @
> org.http4s.client.PoolManager.shutdown(PoolManager.scala:370) at
> uncancelable @
> org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)

> at withPermit @
> org.http4s.client.PoolManager.shutdown(PoolManager.scala:370) at
> guarantee$extension @
> org.http4s.client.blaze.Http1Connection.$anonfun$executeRequest$2(Http1Connection.scala:193)
> at map @
> fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
> Caused by: UnauthorizedError(Bad credentials,
> https://docs.github.com/rest)
> <https://travis-ci.org/github/scanamo/scanamo/jobs/758235897>
>
> Would you mind taking a look?
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scanamo/scanamo/pull/972#issuecomment-776084505>, or

unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAEZZWGH7FRJHGFA3PRDBSTS6FSNHANCNFSM4XK6SHQQ>.

**Comment by regiskuckaertz** [comment]
@davidfurey I think the github token in Travis was incorrect. I have generated a new one and restarted the job, let's see what happens.

**Comment by regiskuckaertz** [comment]
(this is the GITHUB_TOKEN environment variable in the Travis settings)

**Comment by davidfurey** [comment]
Great, it worked.  Thanks for updating the token.

**Pull request merged**
