### PR TITLE
Feature/aws v2

### PR DESCRIPTION
**Pull request by ratoshniuk**

### CODE REVIEW

**Comment by ratoshniuk** [comment]
Fixed #333

**Comment by ratoshniuk** [comment]
Current work with Alpakka is absolutely inconvenient because alpakka uses v1. So i decided to make some wrappers from legacy and back. But it seems to be overhead, and I dunno how to make temporary workaround kinda neat

**Comment by ratoshniuk** [comment]
Also! I make an update  for zio and added docker-compose (i will remove them from this PR) and maybe it also would be OK to rebase master after https://github.com/scanamo/scanamo/pull/329

**Comment by regiskuckaertz** [comment]
Thanks for your great work on this! This ticket is going to be very tricky. Lots of apps are still relying on v1, we don't want to sneakily introduce the v2 sdk there. That would probably create issues at the end of the world anyway. I will review but I'm of the opinion that `ScanamoOps` should be parameterised by the model datatypes, i.e.:
```scala
abstract class ScanamoOps[PutItemResult, GetItemResult, ..., A]
```
and then we could add a `org.scanamo.ops.impl` package where v1 and v2 specialisations would like:
```
import com.amazonaws.services.dynamodbv2.model._
sealed abstract class ScanamoOpsV1[A] extends ScanamoOps[PutItemResult, GetItemResult, ...]
```
and 
```
import software.amazon.awssdk.services.dynamodb.model._
sealed abstract class ScanamoOpsV1[A] extends ScanamoOps[PutItemResponse, GetItemResponse, ...]
```

**Comment by ratoshniuk** [comment]
@ratoshniuk Yeah, that makes sense. Ok, I will do that.

**Comment by TBonnin** [comment]
@regiskuckaertz what about abstracting AWS dynamodb types rather than exposing them to the lib end user. Of course that would be a massive change but we already about to do it. See your comment at https://github.com/scanamo/scanamo/issues/290 ;)

**Comment by ratoshniuk** [comment]
@TBonnin I am currently made an abstraction over AttributeValue. That was a start point

**Comment by ratoshniuk** [comment]
@TBonnin @regiskuckaertz It is really good idea to make an abstraction over amazon. it helps to test all api even without real environment

**Comment by regiskuckaertz** [comment]
Yes I think this is the direction I'd like to move in, ultimately. We could then have unit tests to validate the properties of the library and integration tests using v1 and v2 sdks.

@TBonnin The problem is that we have to deal with two different concrete implementations of the dynamodb model, adding data on top of them will make them invisible to the outside world, but I think the challenge here is also to make the core of the library oblivious to them as well.

**Comment by ratoshniuk** [comment]
@regiskuckaertz i almost finish getting rid of aws deps from `scanamo` and `formats`as well. stay tuned

**Comment by ratoshniuk** [comment]
@TBonnin @regiskuckaertz  Hey guys, it seems I confused and need some help

https://github.com/ratoshniuk/scanamo/blob/289141a74b67daf5d742e18b61973381fb067329/formats/src/main/scala/com/gu/scanamo/DynamoFormat.scala#L530

it can't find any implicit implementations. It seems that

```scala
DynamoFormat[T, V] != DynamoFormatV1[T]

type V = ???
but DynamoFormatV1[T] = DynamoFormat[T, V]
```

**Comment by ratoshniuk** [comment]
As I understand it uses simulacrum to provide companion object with apply. But I didn’t manage to make it works when i put another type arg for DynamoFormat. It is an abstraction over AttributeValue

**Comment by regiskuckaertz** [comment]
Hmm, you can try making an existential type instead:
```scala
trait DynamoFormat[T] { type V }
trait DynamoFormatV1[T] extends DynamoFormat[T] { type V = AttributeValue }
```

**Comment by ratoshniuk** [comment]
@regiskuckaertz V is a typeclass, I can not do that

**Comment by ratoshniuk** [comment]
@regiskuckaertz Please, could you jump into this one and try out my approach?
 #345

It became a completely non-obvious problem for me and I think I can't perform proper abstraction.
And I think it's too silly and redundant as I did.

**Comment by regiskuckaertz** [comment]
Major rework in the pipeline that will significantly simplify this, so closing for now.

Would be thrilled to resume when that is ready. Keep jour eyes peeled

**Pull request closed without merging**
