### PR TITLE
Added overloaded exec to return Future

### PR DESCRIPTION
**Pull request by mavericksid**
Hi @regiskuckaertz 

Do you think returning a Future from exec will be idiomatic? If yes, raised a PR for this addition :)

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
It can't hurt 😉 I wonder though, why would you be using the alpakka client if you can just grab `ScanamoAsync` and directly get a `Future[_]`?

You'll have to run fmt (perhaps you need to pull the latest master, I changed some rules recently)

**Comment by mavericksid** [comment]
That's a good point but doesn't org.scanamo.ScanamoAsync use 
`com.amazonaws.services.dynamodbv2.AmazonDynamoDBAsync`
which is inherently blocking?

https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-x-released/
`The AWS SDK for Java 2.x utilizes a new, nonblocking SDK architecture built on Netty to support true nonblocking I/O. The 1.11.x version already has asynchronous variants of service clients, but they are a managed thread pool on top of the synchronous clients, so each request still requires its own thread. `

and build.sbt contains
`val awsDynamoDB = "com.amazonaws" % "aws-java-sdk-dynamodb" % "1.11.504"`

Moreover, I guess converting to Future will make codebase composable and might reduce boilerplate. What do you think?

**Comment by mavericksid** [comment]
@regiskuckaertz 

Run `scalafmtAll` and fixed the other issues. The changes are good to be reviewed if you think they are useful 😃

**Comment by mavericksid** [comment]
Great! Glad it helped 😄 

Thank you for quick replies 👍

**Pull request merged**
