### PR TITLE
feat(testkit): add LocalDynamoDB methods for creating multi-index tables

### PR DESCRIPTION
**Pull request by razvanz**
Adds LocalDynamoDB methods for creating tables with multiple indexes.

Note: I tried to keep the method signatures consistent, but feel free to suggest something else.

### CODE REVIEW

**Review by kailuowang — APPROVED** [review]

**Comment by sentenza** [comment]
@kailuowang @regiskuckaertz any reason why this PR hasn't been merged yet (after 6 months)?

**Comment by regiskuckaertz** [comment]
hi @sentenza and @razvanz 👋 I don't contribute to this project anymore, although I do think this is a great addition and will give it my stamp of approval!

**Review by regiskuckaertz — APPROVED** [review]

**Comment by regiskuckaertz** [comment]
Ah, since we have to 👍 let's get it merged!

**Comment by sentenza** [comment]
@kailuowang any chance to get a new release with this change added? The last release is dated 2 Nov 2022 https://github.com/scanamo/scanamo/releases/tag/v1.0.0-M23

This change should solve the issue reported  here: https://stackoverflow.com/q/76064934/1977778

**Comment by sentenza** [comment]
> hi @sentenza and @razvanz 👋 I don't contribute to this project anymore, although I do think this is a great addition and will give it my stamp of approval!

Hi @regiskuckaertz, you should definitely change the [CODEOWNERS file](https://github.com/scanamo/scanamo/blob/7df8f0cf4e41195dcaaa3362067e7443e6e64880/CODEOWNERS) then. It seems you are the maintainer of this project. Who's responsible for it right now? Is there anyone else that is actually capable of maintaining the project?

**Comment by kailuowang** [comment]
Release kicked off.

**Pull request merged**
