### PR TITLE
Add Pekko integration module

### PR DESCRIPTION
**Pull request by paul-danilin-moia**
Fixes https://github.com/scanamo/scanamo/issues/1655

### CODE REVIEW

**Comment by kailuowang** [comment]
thanks very much! Just curious, is the whole test suite copied from the akka module? If so, did you add or remove any tests?

**Comment by paul-danilin-moia** [comment]
There is one issue with the module: it is using a snapshot version of Pekko since they haven't published a `1.0.0` yet. The progress should be [here](https://github.com/apache/incubator-pekko/milestone/1). 
My suggestion (if you are to merge and publish the module) would be to publish it as a snapshot, not as a regular version `1.0.0-M*` if this is possible

**Comment by kailuowang** [comment]
We disabled snapshot release a while ago. If they can publish a milestone release we can release one milestone as well.

**Comment by gabetax** [comment]
The pekko core 1.0.0 jars are now live: https://central.sonatype.com/namespace/org.apache.pekko - [release notes](https://pekko.apache.org/docs/pekko/current/release-notes/index.html#1-0-0)

@paul-danilin-moia would you mind bumping your libraryDependencies, and @kailuowang does this look good for release following that?

**Comment by kailuowang** [comment]
I am on vacation right now. Will be back mid August

**Comment by paul-danilin-moia** [comment]
@gabetax here we depend on `pekko-connectors-dynamodb` which is not yet released with 1.0.0: https://pekko.apache.org/docs/pekko-connectors/current/release-notes/

I suspect that the library transitively depends on `pekko-http` and waits for its 1.0.0 release too: https://github.com/apache/incubator-pekko-http/milestone/2

**Comment by paul-danilin-moia** [comment]
I try to monitor the releases once in a while. Feel free to fork/push changes to my branch if the release is ready but I haven't updated the PR. I can miss the moment 😅 Though I am too interested in the scanamo module published as fast as possible.

**Comment by paul-danilin-moia** [comment]
Pekko HTTP is published 🎉 
DynamoDB connector is not yet-_-

**Comment by paul-danilin-moia** [comment]
Now pekko connectors has been released. @kailuowang this should be good to go

**Review by kailuowang — APPROVED** [review]

**Comment by kailuowang** [comment]
@paul-danilin-moia `M27`  released yesterday. Thanks very much again for your contribution.

**Comment by paul-danilin-moia** [comment]
@kailuowang could you please doublecheck that the publication of the module was successful? I can't find the new artefact in maven: https://repo1.maven.org/maven2/org/scanamo/ doesn't show `scanamo-pekko`

**Comment by kailuowang** [comment]
ah, it's not added to the root project. Just submitted a PR https://github.com/scanamo/scanamo/pull/1713

**Pull request merged**
