### PR TITLE
Added set if_not_exists update expression

### PR DESCRIPTION
**Pull request by kacper-marzecki**
Hi there, this PR adds support for the `SET path = if_not_exists(path, :value)` update expression as `UpdateExpression#setIfNotExists`

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
Thank you @kacper-marzecki  this is looking great! Can you please run scalafmt on your code? That will fix the build.

**Review by regiskuckaertz — APPROVED** [review]
That was fast 😄

**Comment by kacper-marzecki** [comment]
Thought I could fix it in the morning before You could notice :)

**Comment by regiskuckaertz** [comment]
Thanks again and congrats on your first Scanamo PR 💪 🕺

**Pull request merged**
