### PR TITLE
Create copy of bytes from SDK

### LINKED ISSUE #959: ReadOnlyBufferException on upgrade
When upgrading from `1.0.0-M9` to `1.0-M14` we are encountering `java.nio.ReadOnlyBufferException` on making a `query` call to DynamoDb.

```
java.nio.ReadOnlyBufferException: null
	at java.nio.ByteBuffer.array(ByteBuffer.java:996)
	at org.scanamo.DynamoFormat$.$anonfun$byteArrayFormat$1(DynamoFormat.scala:192)
	at org.scanamo.DynamoFormat$.$anonfun$coerce$2(DynamoFormat.scala:99)
	at cats.syntax.EitherSyntax$CatchOnlyPartiallyApplied$.apply$extension(either.scala:31)
	at org.scanamo.DynamoFormat$.$anonfun$coerce$1(DynamoFormat.scala:99)
	at scala.util.Either.flatMap(Either.scala:341)
	at org.scanamo.DynamoFormat$$anon$4.read(DynamoFormat.scala:118)
	at org.scanamo.DynamoFormat$$anon$4.read(DynamoFormat.scala:118)
	at org.scanamo.DynamoFormat$$anon$10.read(DynamoFormat.scala:280)
	at org.scanamo.generic.Derivation.$anonfun$combine$5(Derivation.scala:46)
	at scala.Option.fold(Option.scala:251)
	at org.scanamo.generic.Derivation.org$scanamo$generic$Derivation$$decodeField$1(Derivation.scala:46)
	at org.scanamo.generic.Derivation$$anon$2.$anonfun$readObject$1(Derivation.scala:66)
	at cats.Parallel$.$anonfun$parTraverse$1(Parallel.scala:215)
	at cats.data.Chain$.$anonfun$traverseViaChain$3(Chain.scala:708)
	at cats.Eval$.loop$1(Eval.scala:317)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:363)
	at cats.Eval$FlatMap.value(Eval.scala:284)
	at cats.data.Chain$.traverseViaChain(Chain.scala:730)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:96)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:17)
	at cats.Parallel$.parTraverse(Parallel.scala:215)
	at cats.syntax.ParallelTraversableOps$.parTraverse$extension(parallel.scala:112)
	at org.scanamo.generic.Derivation$$anon$2.readObject(Derivation.scala:66)
	at org.scanamo.DynamoFormat$ObjectFormat.$anonfun$read$2(DynamoFormat.scala:82)
	at scala.Option.fold(Option.scala:251)
	at org.scanamo.DynamoFormat$ObjectFormat.read(DynamoFormat.scala:82)
	at org.scanamo.DynamoFormat$ObjectFormat.read$(DynamoFormat.scala:81)
	at org.scanamo.generic.Derivation$$anon$2.read(Derivation.scala:63)
	at org.scanamo.generic.Derivation.$anonfun$combine$5(Derivation.scala:46)
	at scala.Option.fold(Option.scala:251)
	at org.scanamo.generic.Derivation.org$scanamo$generic$Derivation$$decodeField$1(Derivation.scala:46)
	at org.scanamo.generic.Derivation$$anon$2.$anonfun$readObject$1(Derivation.scala:66)
	at cats.Parallel$.$anonfun$parTraverse$1(Parallel.scala:215)
	at cats.data.Chain$.$anonfun$traverseViaChain$3(Chain.scala:708)
	at cats.Eval$.loop$1(Eval.scala:320)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:363)
	at cats.Eval$FlatMap.value(Eval.scala:284)
	at cats.data.Chain$.traverseViaChain(Chain.scala:730)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:96)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:17)
	at cats.Parallel$.parTraverse(Parallel.scala:215)
	at cats.syntax.ParallelTraversableOps$.parTraverse$extension(parallel.scala:112)
	at org.scanamo.generic.Derivation$$anon$2.readObject(Derivation.scala:66)
	at org.scanamo.DynamoFormat$ObjectFormat.$anonfun$read$2(DynamoFormat.scala:82)
	at scala.Option.fold(Option.scala:251)
	at org.scanamo.DynamoFormat$ObjectFormat.read(DynamoFormat.scala:82)
	at org.scanamo.DynamoFormat$ObjectFormat.read$(DynamoFormat.scala:81)
	at org.scanamo.generic.Derivation$$anon$2.read(Derivation.scala:63)
	at org.scanamo.ScanamoFree$.read(ScanamoFree.scala:232)
	at org.scanamo.DynamoResultStream.$anonfun$stream$2(DynamoResultStream.scala:43)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.scanamo.DynamoResultStream.$anonfun$stream$1(DynamoResultStream.scala:43)
	at cats.free.Free.$anonfun$map$1(Free.scala:18)
	at cats.free.Free.$anonfun$step$1(Free.scala:55)
	at cats.free.Free.$anonfun$foldMap$3(Free.scala:146)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The records being received do contain `java.net.InetAddress` value that we map to a `Array[Byte]` using the following `DynamoFormat`

```
implicit val inetAddressLongFormat: DynamoFormat[InetAddress] = DynamoFormat.coercedXmap[InetAddress, Array[Byte], IllegalArgumentException](
    { InetAddress.getByAddress }, {_.getAddress}
  )
```

Any idea what change might be causing this and how to mitigate it? We have data written from the previous versions that we need to be able to read.

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Fixes #959 

Looks like the SDK is creating a read-only bytebuffer.

### CODE REVIEW

**Comment by shayangz** [comment]
Thanks @regiskuckaertz . any guidance on when we can expect this merged and released?

**Comment by davidfurey** [comment]
Thanks for fixing this bug Regis!  The test you added passes without your other changes, and I haven't had a chance to try reproducing the bug Shayan reported.  But since the change looks fairly safe I'm happy to +1 if you or Shayan have checked that this does indeed resolve #959

**Comment by shayangz** [comment]
I have confirmed that this PR fixes the bug @davidfurey @regiskuckaertz 🙏

**Comment by davidfurey** [comment]
Great, thanks for confirming.  I'll merge now and release next week.

**Pull request merged**
