### PR TITLE
Add an option to query tables in reverse order.

### PR DESCRIPTION
**Pull request by jcohen**
This should address #267. Please let me know if I missed adding support for this anywhere (e.g. does it need to be added to the top level Scanamo/ScanamoAsync/etc.), or if more tests are needed, etc.!

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
Hi @jcohen 

This is actually supported already, but the combinator is on the condition instead of the table:
```scala
table.query(('key -> value).descending)
```
The reason is that it only works for queries, not scans, and with this PR someone could do `table.reverse.scan(...)` even if it does not make sense.

From a usability POV, I think it makes sense to move that in the table API though. However we need to find a solution to prevent the kind of degenerate case as above. I see two:

1. create a `TableQueryOnlyOptions[V]` that only permits queries: there will be duplication but will get the job done
2. reverse the ordering in the expression, i.e. `table.query(...).reverse`. This requires more effort but is the right thing to do I believe. For example in this case, we could introduce a new primitive to `ScanamoOpsA`:

```scala
final case class Reverse(query: ScanamoOps[QueryResult]) extends ScanamoOps[QueryResult]
```
then add a case to the interpreters:
```scala
case Revere(query) =>
  val q = query.asInstanceOf[Query]
  val r = q.req.withScanForward(false)
  apply(Query(r))
```
How does that sound?

**Comment by regiskuckaertz** [comment]
I'm tempted to close this PR for now until we get 1.0 out, after which we can start thinking of an API overhaul for v2.

**Comment by jcohen** [comment]
Sorry for the delayed response.

@regiskuckaertz I think that's fair. The existing functionality (using `.descending` on the key) works well enough for now.

I'm not sure how I missed it to begin with. I swear I grepped the codebase for `scanIndexForward` before throwing this together ;).

**Comment by toidiu** [comment]
I have a scenario where I have a partition key(P) and a sort key(S). I want the query:
`('P = value) and ('S -> descending)`

Am I missing something or is there a way to do this with the `.descending` syntax.

**Pull request closed without merging**
